tags:
- name: Owner Tokens
  description: API to fetch the tokens of owner

paths:
# [GET] users
  /:
    get:
      tags:
      - erc721
      summary: Get token ids along with the metadata uri link and metadata for all the tokens 
      parameters:
      - name: owner
        in: query
        description: user's ethereum wallet address
        required: true
        schema:
          $ref: '#/definitions/owner'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Invalid request'
        500:
          description: 'Server Error'

# definitions
definitions:
  owner:
    type: string
    description: Owner's ethereum wallet address

schemes:
 - http
